# Data Preprocessing

#### By: Reema Domadia

##### Dataset requires high computation power, this part of the project focuses on scaling down the dataset

In [41]:
import pandas as pd
import sys
read_file = pd.read_csv('/Users/ramanlaldomadia/Desktop/Capstone/all-the-news-2-1.csv', nrows=1000)
read_file.shape
print("----Dataset Information----")
read_file.info()
print("----Glimpse of Dataset----")
print("An integer takes", sys.getsizeof(read_file), "bytes")
read_file.head(3)

----Dataset Information----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
Unnamed: 0      1000 non-null int64
Unnamed: 0.1    1000 non-null int64
date            1000 non-null object
year            1000 non-null int64
month           1000 non-null float64
day             1000 non-null int64
author          694 non-null object
title           1000 non-null object
article         998 non-null object
url             1000 non-null object
section         441 non-null object
publication     1000 non-null object
dtypes: float64(1), int64(4), object(7)
memory usage: 93.9+ KB
----Glimpse of Dataset----
An integer takes 8154983 bytes

,Unnamed: 0,Unnamed: 0.1,date,year,month,day,author,title,article,url,section,publication
0,0,0,2016-12-09 18:31:00,2016,12.0,9,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",https://www.vox.com/polyarchy/2016/12/9/138983...,NaN,Vox
1,1,1,2016-10-07 21:26:46,2016,10.0,7,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,https://www.businessinsider.com/colts-gm-ryan-...,NaN,Business Insider
2,2,2,2018-01-26 00:00:00,2018,1.0,26,NaN,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",https://www.reuters.com/article/us-davos-meeti...,Davos,Reuters

In [42]:
read_file=read_file.drop(columns=['section','Unnamed: 0.1','Unnamed: 0', 'url'])
print(read_file.columns)

Index(['date', 'year', 'month', 'day', 'author', 'title', 'article',
       'publication'],
      dtype='object')

In [43]:
read_file['date'] = read_file['date'].str[-8:]
read_file=read_file.rename(columns={"date": "time"})
read_file.head(5)

,time,year,month,day,author,title,article,publication
0,18:31:00,2016,12.0,9,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",Vox
1,21:26:46,2016,10.0,7,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,Business Insider
2,00:00:00,2018,1.0,26,NaN,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",Reuters
3,00:00:00,2019,6.0,27,NaN,France's Sarkozy reveals his 'Passions' but in...,PARIS (Reuters) - Former French president Nico...,Reuters
4,00:00:00,2016,1.0,27,NaN,Paris Hilton: Woman In Black For Uncle Monty's...,Paris Hilton arrived at LAX Wednesday dressed ...,TMZ

In [44]:
read_file['month']=read_file['month'].astype(int)
read_file['title']=read_file['title'].astype(str)
read_file['author']=read_file['author'].astype(str)
read_file['article']=read_file['article'].astype(str)
read_file['publication']=read_file['publication'].astype(str)
read_file.dtypes

time           object
year            int64
month           int64
day             int64
author         object
title          object
article        object
publication    object
dtype: object

In [45]:
#List of Publications
read_file['publication'].unique()

array(['Vox', 'Business Insider', 'Reuters', 'TMZ', 'Vice', 'Vice News',
       'Hyperallergic'], dtype=object)

In [46]:
#Combine Varients 

#Combine Vice and Vice News

In [47]:
#List of Top Publications
a=15 #Top n number of publications in the dataset
s=read_file['publication'].value_counts().nlargest(a).index.tolist()
print("List of Top Publications:", s)

List of Top Publications: ['Reuters', 'Vox', 'Vice', 'TMZ', 'Vice News', 'Hyperallergic', 'Business Insider']

In [48]:
#keep top 15 (of 27) publications, remove everything else
read_file=read_file.loc[read_file['publication'].isin(s)]
read_file.head(5)

,time,year,month,day,author,title,article,publication
0,18:31:00,2016,12,9,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",Vox
1,21:26:46,2016,10,7,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,Business Insider
2,00:00:00,2018,1,26,nan,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",Reuters
3,00:00:00,2019,6,27,nan,France's Sarkozy reveals his 'Passions' but in...,PARIS (Reuters) - Former French president Nico...,Reuters
4,00:00:00,2016,1,27,nan,Paris Hilton: Woman In Black For Uncle Monty's...,Paris Hilton arrived at LAX Wednesday dressed ...,TMZ

In [49]:
#Reorder Variables
read_file = read_file[["month", "day", "year", "time", "author", "title", "article", "publication"]]
read_file

#Create Date variable - month, day, year
#Clean up: Drop month, day, year
read_file['date'] = read_file[read_file.columns[:3]].apply(
    lambda x: '/'.join(x.dropna().astype(str)),
    axis=1)
read_file=read_file.drop(columns=['day','month','year'])
read_file = read_file[["date", "time", "author", "title", "article", "publication"]]

read_file

#Create Date/Time variable - month, day, year, time
#Clean up: Drop time
read_file['date/time'] = read_file[read_file.columns[:2]].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)
read_file=read_file.drop(columns=['time'])
read_file = read_file[["date", 'date/time', "author", "title", "article", "publication"]]
read_file

,date,date/time,author,title,article,publication
0,12/9/2016,12/9/2016 18:31:00,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",Vox
1,10/7/2016,10/7/2016 21:26:46,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,Business Insider
2,1/26/2018,1/26/2018 00:00:00,nan,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",Reuters
3,6/27/2019,6/27/2019 00:00:00,nan,France's Sarkozy reveals his 'Passions' but in...,PARIS (Reuters) - Former French president Nico...,Reuters
4,1/27/2016,1/27/2016 00:00:00,nan,Paris Hilton: Woman In Black For Uncle Monty's...,Paris Hilton arrived at LAX Wednesday dressed ...,TMZ
...,...,...,...,...,...,...
995,11/3/2017,11/3/2017 12:01:00,Tanza Loudenback,Inside a Los Angeles apartment that rents for ...,The most expensive apartment for rent in Los A...,Business Insider
996,9/21/2017,9/21/2017 15:18:21,John Lynch,Netflix and Escobar family in a trademark figh...,Netflix has been in an ongoing trademark dispu...,Business Insider
997,11/5/2017,11/5/2017 00:00:00,David Shepardson,Democratic leader vows fair nomination process...,WASHINGTON (Reuters) - The head of the Democra...,Reuters
998,6/14/2018,6/14/2018 18:15:57,Marilyn La Jeunesse,I honor my single mom and all single mothers o...,"Father's Day has traditionally, and understan...",Business Insider
999,8/29/2016,8/29/2016 00:00:00,nan,FS1 Trolls ESPN With Skip Bayless Billboards,Skip Bayless just left ESPN -- but he still li...,TMZ

In [50]:
read_file.nunique()

date           638
date/time      835
author         453
title          999
article        996
publication      7
dtype: int64

In [51]:
#Drop Duplicates
read_file=read_file.drop_duplicates()
read_file

,date,date/time,author,title,article,publication
0,12/9/2016,12/9/2016 18:31:00,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",Vox
1,10/7/2016,10/7/2016 21:26:46,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,Business Insider
2,1/26/2018,1/26/2018 00:00:00,nan,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",Reuters
3,6/27/2019,6/27/2019 00:00:00,nan,France's Sarkozy reveals his 'Passions' but in...,PARIS (Reuters) - Former French president Nico...,Reuters
4,1/27/2016,1/27/2016 00:00:00,nan,Paris Hilton: Woman In Black For Uncle Monty's...,Paris Hilton arrived at LAX Wednesday dressed ...,TMZ
...,...,...,...,...,...,...
995,11/3/2017,11/3/2017 12:01:00,Tanza Loudenback,Inside a Los Angeles apartment that rents for ...,The most expensive apartment for rent in Los A...,Business Insider
996,9/21/2017,9/21/2017 15:18:21,John Lynch,Netflix and Escobar family in a trademark figh...,Netflix has been in an ongoing trademark dispu...,Business Insider
997,11/5/2017,11/5/2017 00:00:00,David Shepardson,Democratic leader vows fair nomination process...,WASHINGTON (Reuters) - The head of the Democra...,Reuters
998,6/14/2018,6/14/2018 18:15:57,Marilyn La Jeunesse,I honor my single mom and all single mothers o...,"Father's Day has traditionally, and understan...",Business Insider
999,8/29/2016,8/29/2016 00:00:00,nan,FS1 Trolls ESPN With Skip Bayless Billboards,Skip Bayless just left ESPN -- but he still li...,TMZ

In [52]:
#Drop no data ----- HELPPP!!! Ideally we want all observations to have all data.
read_file.fillna(0)

,date,date/time,author,title,article,publication
0,12/9/2016,12/9/2016 18:31:00,Lee Drutman,We should take concerns about the health of li...,"This post is part of Polyarchy, an independent...",Vox
1,10/7/2016,10/7/2016 21:26:46,Scott Davis,Colts GM Ryan Grigson says Andrew Luck's contr...,The Indianapolis Colts made Andrew Luck the h...,Business Insider
2,1/26/2018,1/26/2018 00:00:00,nan,Trump denies report he ordered Mueller fired,"DAVOS, Switzerland (Reuters) - U.S. President ...",Reuters
3,6/27/2019,6/27/2019 00:00:00,nan,France's Sarkozy reveals his 'Passions' but in...,PARIS (Reuters) - Former French president Nico...,Reuters
4,1/27/2016,1/27/2016 00:00:00,nan,Paris Hilton: Woman In Black For Uncle Monty's...,Paris Hilton arrived at LAX Wednesday dressed ...,TMZ
...,...,...,...,...,...,...
995,11/3/2017,11/3/2017 12:01:00,Tanza Loudenback,Inside a Los Angeles apartment that rents for ...,The most expensive apartment for rent in Los A...,Business Insider
996,9/21/2017,9/21/2017 15:18:21,John Lynch,Netflix and Escobar family in a trademark figh...,Netflix has been in an ongoing trademark dispu...,Business Insider
997,11/5/2017,11/5/2017 00:00:00,David Shepardson,Democratic leader vows fair nomination process...,WASHINGTON (Reuters) - The head of the Democra...,Reuters
998,6/14/2018,6/14/2018 18:15:57,Marilyn La Jeunesse,I honor my single mom and all single mothers o...,"Father's Day has traditionally, and understan...",Business Insider
999,8/29/2016,8/29/2016 00:00:00,nan,FS1 Trolls ESPN With Skip Bayless Billboards,Skip Bayless just left ESPN -- but he still li...,TMZ

In [53]:
print("New shape of dataframe (rows, columns):",read_file.shape)

New shape of dataframe (rows, columns): (1000, 6)

In [54]:
print("An integer takes", sys.getsizeof(read_file), "bytes")

An integer takes 11703931 bytes

In [55]:
#Save file
read_file.to_excel("news_data.xlsx")